package com.example.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendao.ExampleEntity;
import com.example.greendao.entity.StudentEntity;

import com.example.greendao.dao.ExampleEntityDao;
import com.example.greendao.dao.StudentEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exampleEntityDaoConfig;
    private final DaoConfig studentEntityDaoConfig;

    private final ExampleEntityDao exampleEntityDao;
    private final StudentEntityDao studentEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exampleEntityDaoConfig = daoConfigMap.get(ExampleEntityDao.class).clone();
        exampleEntityDaoConfig.initIdentityScope(type);

        studentEntityDaoConfig = daoConfigMap.get(StudentEntityDao.class).clone();
        studentEntityDaoConfig.initIdentityScope(type);

        exampleEntityDao = new ExampleEntityDao(exampleEntityDaoConfig, this);
        studentEntityDao = new StudentEntityDao(studentEntityDaoConfig, this);

        registerDao(ExampleEntity.class, exampleEntityDao);
        registerDao(StudentEntity.class, studentEntityDao);
    }
    
    public void clear() {
        exampleEntityDaoConfig.clearIdentityScope();
        studentEntityDaoConfig.clearIdentityScope();
    }

    public ExampleEntityDao getExampleEntityDao() {
        return exampleEntityDao;
    }

    public StudentEntityDao getStudentEntityDao() {
        return studentEntityDao;
    }

}
